[package]
name = "data-manipulation"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal_toolbox = { git = "https://github.com/AlbinDalbert/Terminal-Toolbox.git" }